In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
d=pd.read_csv('Car_sales.csv')

In [4]:
d.sample(20)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
78,Lincoln,Navigator,22.925,NaN,Car,42.660,5.4,300.0,119.0,79.9,204.8,5.393,30.0,15.0,12/23/2012,123.972047
65,Infiniti,I30,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,4/15/2012,92.436889
43,Dodge,Dakota,111.313,11.260,Car,16.980,2.5,120.0,131.0,71.5,215.0,3.557,22.0,19.0,11/25/2011,49.645002
127,Saab,5-Sep,9.191,NaN,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
23,Chevrolet,Camaro,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,10/23/2011,81.118543
104,Nissan,Quest,27.308,15.380,Car,26.399,3.3,170.0,112.2,74.9,194.8,3.991,20.0,21.0,3/7/2011,71.171664
74,Lexus,LX470,9.126,NaN,Car,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0,10/30/2012,105.760458
139,Toyota,Celica,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
33,Chrysler,Town & Country,53.480,19.540,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/13/2011,NaN
128,Saab,3-Sep,12.115,NaN,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
54,Ford,Expedition,125.338,23.575,Car,36.135,4.6,240.0,119.0,78.7,204.6,4.808,26.0,16.0,9/14/2012,100.024802
155,Volvo,C70,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
24,Chevrolet,Corvette,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,5/12/2012,141.141150
50,Ford,Focus,175.670,NaN,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
110,Oldsmobile,Alero,80.255,NaN,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
132,Saturn,LW,8.472,NaN,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
82,Mitsubishi,Diamante,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,8/28/2012,84.830779
112,Oldsmobile,Bravada,20.017,19.925,Car,31.598,4.3,190.0,107.0,67.8,181.2,4.068,17.5,19.0,9/21/2011,80.511673
0,Acura,Integra,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
39,Dodge,Viper,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323

# drop Na

In [5]:
d.dropna(inplace=True)
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 117 entries, 0 to 149
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         117 non-null    object
 1   Model                117 non-null    object
 2   Sales_in_thousands   117 non-null    float64
 3   __year_resale_value  117 non-null    float64
 4   Vehicle_type         117 non-null    object
 5   Price_in_thousands   117 non-null    float64
 6   Engine_size          117 non-null    float64
 7   Horsepower           117 non-null    float64
 8   Wheelbase            117 non-null    float64
 9   Width                117 non-null    float64
 10  Length               117 non-null    float64
 11  Curb_weight          117 non-null    float64
 12  Fuel_capacity        117 non-null    float64
 13  Fuel_efficiency      117 non-null    float64
 14  Latest_Launch        117 non-null    object
 15  Power_perf_factor    117 non-null    float64
dtypes: float64(12), object(4)
memory usage: 15.5+ KB

#### Checking The contents in latest launch column

In [7]:
# unique fuction use as to list down unique values in a column

In [8]:
d.Latest_Launch.unique()

array(['2/2/2012', '6/3/2011', '3/10/2011', '10/8/2011', '8/9/2011',
       '2/27/2012', '1/29/2012', '4/4/2011', '11/2/2011', '9/3/2011',
       '3/23/2012', '7/23/2011', '2/23/2012', '11/27/2011', '9/28/2011',
       '8/17/2011', '3/19/2012', '5/24/2011', '12/22/2011', '10/23/2011',
       '5/12/2012', '9/11/2011', '4/13/2012', '1/16/2012', '11/17/2011',
       '6/6/2012', '10/6/2011', '5/8/2012', '12/12/2011', '7/1/2012',
       '10/31/2011', '8/7/2011', '3/6/2012', '1/6/2012', '7/26/2012',
       '11/25/2011', '9/1/2011', '3/31/2012', '1/31/2012', '8/20/2012',
       '12/20/2011', '9/26/2011', '4/25/2012', '2/25/2012', '9/14/2012',
       '1/14/2012', '8/16/2012', '10/21/2011', '5/20/2012', '3/21/2012',
       '10/9/2012', '2/8/2012', '9/10/2012', '11/15/2011', '6/14/2012',
       '4/15/2012', '3/4/2012', '10/5/2012', '12/10/2011', '7/9/2012',
       '5/10/2012', '3/29/2012', '8/3/2012', '6/4/2012', '4/23/2012',
       '11/24/2012', '8/28/2012', '6/29/2012', '1/17/2012', '5/18/2012',
       '12/19/2012', '9/22/2012', '7/24/2012', '2/13/2008', '10/20/2009',
       '4/24/2011', '7/12/2011', '6/13/2011', '3/17/2011', '8/31/2011',
       '8/2/2011', '5/6/2011', '3/7/2011', '9/25/2011', '5/31/2011',
       '2/18/2011', '9/21/2011', '6/25/2011', '4/26/2011', '11/14/2011',
       '1/25/2012', '11/26/2012', '6/16/2012', '10/15/2012', '5/18/2011',
       '2/19/2012', '12/21/2012', '7/11/2011', '3/16/2011', '1/15/2011',
       '4/11/2011', '2/10/2011', '12/29/2012', '8/1/2011', '1/24/2011',
       '8/27/2011', '10/30/2012', '4/1/2011'], dtype=object)

#### Change its dtype into date time

In [9]:
d['Latest_Launch']=pd.to_datetime(d.Latest_Launch)

In [10]:
d.head(20)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2012-02-02,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,2011-06-03,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2011-03-10,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,2011-10-08,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,2011-08-09,84.565105
6,Audi,A8,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2012-02-27,134.656858
8,BMW,328i,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,2012-01-29,81.877069
9,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,2011-04-04,83.998724
10,Buick,Century,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,2011-11-02,71.181451
11,Buick,Regal,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,2011-09-03,95.636703
12,Buick,Park Avenue,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,2012-03-23,85.828408
13,Buick,LeSabre,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,2011-07-23,84.254526
14,Cadillac,DeVille,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2012-02-23,113.854598
16,Cadillac,Eldorado,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,2011-11-27,113.765874
17,Cadillac,Catera,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,2011-09-28,83.483094
19,Chevrolet,Cavalier,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,2011-08-17,46.363347
20,Chevrolet,Malibu,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,2012-03-19,67.314462
21,Chevrolet,Lumina,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,2011-05-24,69.991396
22,Chevrolet,Monte Carlo,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,2011-12-22,72.030917
23,Chevrolet,Camaro,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,2011-10-23,81.118543

#### Check the dtype in it

In [11]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 117 entries, 0 to 149
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         117 non-null    object
 1   Model                117 non-null    object
 2   Sales_in_thousands   117 non-null    float64
 3   __year_resale_value  117 non-null    float64
 4   Vehicle_type         117 non-null    object
 5   Price_in_thousands   117 non-null    float64
 6   Engine_size          117 non-null    float64
 7   Horsepower           117 non-null    float64
 8   Wheelbase            117 non-null    float64
 9   Width                117 non-null    float64
 10  Length               117 non-null    float64
 11  Curb_weight          117 non-null    float64
 12  Fuel_capacity        117 non-null    float64
 13  Fuel_efficiency      117 non-null    float64
 14  Latest_Launch        117 non-null    datetime64[ns]
 15  Power_perf_factor    117 non-null    float64
dtypes: datetime64[ns](1), float64(12), object(3)
memory usage: 15.5+ KB

## we can see that it have changed to date time 64[ns] format.

In [12]:
d['Year']=pd.DatetimeIndex(d.Latest_Launch).year

In [13]:
d.sample(10)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor,Year
92,Mercedes-B,C-Class,18.392,26.050,Passenger,31.750,2.3,185.0,105.9,67.7,177.4,3.250,16.4,26.0,2011-04-24,78.280731,2011
9,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,2011-04-04,83.998724,2011
24,Chevrolet,Corvette,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,2012-05-12,141.141150,2012
54,Ford,Expedition,125.338,23.575,Car,36.135,4.6,240.0,119.0,78.7,204.6,4.808,26.0,16.0,2012-09-14,100.024802,2012
122,Pontiac,Bonneville,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,2011-05-18,82.661356,2011
1,Acura,TL,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,2011-06-03,91.370778,2011
59,Honda,CR-V,73.203,17.710,Car,20.550,2.0,146.0,103.2,68.9,177.6,3.219,15.3,24.0,2012-03-21,60.087967,2012
48,Ford,Contour,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,2012-08-20,67.351011,2012
21,Chevrolet,Lumina,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,2011-05-24,69.991396,2011
119,Pontiac,Grand Am,131.097,10.290,Passenger,19.720,3.4,175.0,107.0,70.4,186.3,3.091,15.2,25.0,2012-11-26,70.389737,2012

In [14]:
d['month']=pd.DatetimeIndex(d.Latest_Launch).month

In [15]:
d.sample(20)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor,Year,month
77,Lincoln,Town car,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,2012-06-04,93.957917,2012,6
126,Porsche,Carrera Cabrio,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,2011-07-11,135.914710,2011,7
148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,2011-05-31,48.907372,2011,5
69,Jeep,Grand Cherokee,157.040,18.810,Car,26.895,4.0,195.0,105.9,72.3,181.5,3.880,20.5,19.0,2011-12-10,80.387779,2011,12
14,Cadillac,DeVille,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2012-02-23,113.854598,2012,2
95,Mercedes-B,SL-Class,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,2011-03-17,139.982294,2011,3
86,Mercury,Mystique,14.351,8.800,Passenger,16.240,2.0,125.0,106.5,69.1,184.8,2.769,15.0,28.0,2012-12-19,50.997748,2012,12
76,Lincoln,Continental,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,2012-08-03,113.540207,2012,8
140,Toyota,Tacoma,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,2011-08-01,55.297117,2011,8
46,Ford,Escort,70.227,7.425,Passenger,12.070,2.0,110.0,98.4,67.0,174.7,2.468,12.7,30.0,2012-03-31,44.083709,2012,3
61,Honda,Odyssey,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2012-02-08,85.217691,2012,2
146,Volkswagen,Jetta,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,2011-08-27,47.638237,2011,8
45,Dodge,Caravan,181.749,12.025,Car,19.565,2.4,150.0,113.3,76.8,186.3,3.533,20.0,24.0,2011-09-01,61.227000,2011,9
22,Chevrolet,Monte Carlo,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,2011-12-22,72.030917,2011,12
32,Chrysler,LHS,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,2012-05-08,101.329281,2012,5
36,Dodge,Avenger,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,2012-07-01,65.650508,2012,7
91,Mercury,Villager,20.380,14.795,Car,22.510,3.3,170.0,112.2,74.9,194.7,3.944,20.0,21.0,2009-10-20,69.671461,2009,10
111,Oldsmobile,Aurora,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2011-02-18,103.441693,2011,2
29,Chrysler,Sebring Conv.,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,2011-11-17,69.521355,2011,11
121,Pontiac,Grand Prix,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,2012-10-15,78.318168,2012,10

In [18]:
d['day']=pd.DatetimeIndex(d.Latest_Launch).day

In [19]:
d.sample(35)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor,Year,month,day
81,Mitsubishi,Galant,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,2012-01-29,58.606773,2012,1,29
89,Mercury,Grand Marquis,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,2012-07-24,80.657696,2012,7,24
65,Infiniti,I30,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,2012-04-15,92.436889,2012,4,15
30,Chrysler,Concorde,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,2012-06-06,80.023782,2012,6,6
77,Lincoln,Town car,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,2012-06-04,93.957917,2012,6,4
140,Toyota,Tacoma,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,2011-08-01,55.297117,2011,8,1
24,Chevrolet,Corvette,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,2012-05-12,141.141150,2012,5,12
69,Jeep,Grand Cherokee,157.040,18.810,Car,26.895,4.0,195.0,105.9,72.3,181.5,3.880,20.5,19.0,2011-12-10,80.387779,2011,12,10
57,Honda,Civic,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,2011-10-21,42.879097,2011,10,21
80,Mitsubishi,Eclipse,42.541,10.395,Passenger,19.047,2.4,154.0,100.8,68.9,175.4,2.910,15.9,24.0,2012-11-24,62.441962,2012,11,24
40,Dodge,Ram Pickup,227.061,15.060,Car,19.460,5.2,230.0,138.7,79.3,224.2,4.470,26.0,17.0,2012-03-06,90.211700,2012,3,6
120,Pontiac,Firebird,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,2012-06-16,81.492726,2012,6,16
31,Chrysler,Cirrus,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,2011-10-06,53.566200,2011,10,6
25,Chevrolet,Prizm,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,2011-09-11,48.297636,2011,9,11
67,Jeep,Wrangler,55.557,13.475,Car,14.460,2.5,120.0,93.4,66.7,152.0,3.045,19.0,17.0,2012-03-04,48.672898,2012,3,4
84,Mitsubishi,Montero,11.337,19.125,Car,31.807,3.5,200.0,107.3,69.9,186.6,4.520,24.3,18.0,2012-01-17,83.920815,2012,1,17
19,Chevrolet,Cavalier,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,2011-08-17,46.363347,2011,8,17
16,Cadillac,Eldorado,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,2011-11-27,113.765874,2011,11,27
73,Lexus,LS400,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,2012-03-29,124.446716,2012,3,29
20,Chevrolet,Malibu,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,2012-03-19,67.314462,2012,3,19
145,Volkswagen,Golf,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,2011-01-24,46.943877,2011,1,24
29,Chrysler,Sebring Conv.,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,2011-11-17,69.521355,2011,11,17
101,Nissan,Sentra,42.643,8.450,Passenger,13.499,1.8,126.0,99.8,67.3,177.5,2.593,13.2,30.0,2011-08-31,50.241978,2011,8,31
48,Ford,Contour,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,2012-08-20,67.351011,2012,8,20
36,Dodge,Avenger,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,2012-07-01,65.650508,2012,7,1
70,Lexus,ES300,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,2012-07-09,87.211001,2012,7,9
3,Acura,RL,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2011-03-10,91.389779,2011,3,10
139,Toyota,Celica,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,2012-12-29,56.496030,2012,12,29
116,Plymouth,Voyager,24.155,12.025,Car,18.850,2.4,150.0,113.3,76.8,186.3,3.528,20.0,24.0,2011-04-24,60.951185,2011,4,24
138,Toyota,Avalon,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,2011-08-31,84.911898,2011,8,31
142,Toyota,RAV4,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,2011-05-06,51.955109,2011,5,6
121,Pontiac,Grand Prix,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,2012-10-15,78.318168,2012,10,15
131,Saturn,SW,5.223,10.790,Passenger,14.290,1.9,124.0,102.4,66.4,176.9,2.452,12.1,31.0,2011-01-15,49.865774,2011,1,15
62,Hyundai,Accent,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,65.7,166.7,2.240,11.9,31.0,2012-09-10,36.672284,2012,9,10
149,Volkswagen,GTI,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,2011-04-01,47.946841,2011,4,1

## Converting Numerical into catagorical Column
#### Lets Convert The month numbers into thair corresponding names

In [20]:
d.month.replace({
    1:'Jan',
    2:"Feb",
    3:'Mar',
    4:'Apr',
    5:'May',
    6:'Jun',
    7:'Jul',
    8:'Aug',
    9:'Sep',
    10:'Oct',
    11:'Nov',
    12:'Dec,'
},inplace=True
)

In [23]:
d.sample(10)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor,Year,month,day
16,Cadillac,Eldorado,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,2011-11-27,113.765874,2011,Nov,27
11,Buick,Regal,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,2011-09-03,95.636703,2011,Sep,3
82,Mitsubishi,Diamante,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,2012-08-28,84.830779,2012,Aug,28
113,Oldsmobile,Silhouette,24.361,15.240,Car,25.345,3.4,185.0,120.0,72.2,201.4,3.948,25.0,22.0,2011-06-25,76.096570,2011,Jun,25
103,Nissan,Maxima,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,2011-05-06,89.427820,2011,May,6
47,Ford,Mustang,113.369,12.760,Passenger,21.560,3.8,190.0,101.3,73.1,183.2,3.203,15.7,24.0,2012-01-31,76.509185,2012,Jan,31
28,Chrysler,Sebring Coupe,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,2012-01-16,65.957184,2012,Jan,16
24,Chevrolet,Corvette,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,2012-05-12,141.141150,2012,May,12
85,Mitsubishi,Montero Sport,39.348,13.880,Car,22.527,3.0,173.0,107.3,66.7,178.3,3.510,19.5,20.0,2012-05-18,70.660942,2012,May,18
6,Audi,A8,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2012-02-27,134.656858,2012,Feb,27

# Label encoder

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
l=LabelEncoder()

In [ ]:
d['']